### ISSUE TITLE
merge those module has the same name but in different categories

### ISSUE THREAD

**Issue by wuang1992** [krisztianb/typedoc-plugin-merge-modules#11]
hi, thx you for this plugin. is there any possible can add an option to prevent merge those same name modules which in different categories?

**Comment by krisztianb** [comment]
Hi. Could you give me an example? I guess you are talking about the `@category` doc comment which is [described here](https://typedoc.org/guides/doccomments/#%40category).

**Comment by wuang1992** [comment]
> Hi. Could you give me an example? I guess you are talking about the `@category` doc comment which is [described here](https://typedoc.org/guides/doccomments/#%40category).

Yes, what I am saying is the @category tag, when two files have different category names but the same module name, the plugin will merge them, which I don't want. 

```ts
//  a.ts
/**
* @category a
* @module test
*/

// b.ts
/**
* @category b
* @module test
*/
```

**Comment by krisztianb** [comment]
Ok, thanks for the clarification. I'll look into this and report back to you.

**Comment by krisztianb** [comment]
Well this wasn't hard at all, but it took some time since I also updated to the latest TypeDoc version which totally broke the plugin. I had to fix those issues first...

In release **4.0.0** you can now set the option `mergeModulesMergeMode` to `module-category` to merge only modules with the same category. However you will have to update to TypeDoc 0.23.x to use the new release.

I'd appreciate if you report back whether the plugin works as intended by you or if you run into any problems. Thanks.

**Comment by wuang1992** [comment]
> Well this wasn't hard at all, but it took some time since I also updated to the latest TypeDoc version which totally broke the plugin. I had to fix those issues first...
> 
> In release **4.0.0** you can now set the option `mergeModulesMergeMode` to `module-category` to merge only modules with the same category. However you will have to update to TypeDoc 0.23.x to use the new release.
> 
> I'd appreciate if you report back whether the plugin works as intended by you or if you run into any problems. Thanks.

OK, I will update to the new version. if there have any problem ,i will report back.
