### ISSUE TITLE
Error when running typedoc

### ISSUE THREAD

**Issue by slalum** [krisztianb/typedoc-plugin-merge-modules#4]
When running typedoc I'm getting the following error:

The plugin C:\**\**\base\node_modules\typedoc-plugin-merge-modules could not be loaded.
Error: C:\**\**\base\node_modules\marked\src\marked.js:158
          const prevRenderer = extensions.renderers?.[ext.name];

**Comment by krisztianb** [comment]
I don't think the problem is related to this plugin. Looks like the error happens in the code of Marked.

What have you tried to resolve the issue? I have some suggestions:

* Remove the plugin and see if the problem persists
* Try to install another plugin and see if the problem is the same

Btw. What is `const prevRenderer = extensions.renderers?.[ext.name];`? I that line 158 from the `marked.js` file?

**Comment by slalum** [comment]
The error happens after installing the plugin (The plugin could not be loaded). Without the plugin 'typedoc' works.
I have another typedoc plugin that is loaded.

 I tried changing node version with no success.
